apiVersion: v1
kind: Secret
metadata:
  name: smp-db-secrets
type: Opaque
stringData:
  name: smp_db
  user: smp_user
  password: smp_password
  host: db
  secret_key: "django-insecure-demo-key-for-smp-project-2024"
